title: "Team Blog"
description: "Thoughts, notes, and experiments."
baseurl: "blog" # For user site, leave empty
url: "https://ev1l0rg.github.io/blog"
 
theme: minima
 
author:
  name: "Yo"
  email: "yo@yo.com"
